### ISSUE TITLE
Avance del proyecto

### ISSUE THREAD

**Issue by LanderU** [AlbertoNietoGochicoa/DI_ProyectoFinal#6]
- [x] Añadir métodos entre la BD y visual.

**Comment by AlbertoNietoGochicoa** [comment]
Buenos días Lander, 

He estado intentando hacer la p.. inserción y no soy capaz. El VB no tiene tipo float, al menos no sale entre sus tipos, pero lo he intentado hacer pasandolos a int que debiera de funcionar y tp.
Echale si quieres un vistazo y ya me comentaras si le ves algo. He empujado todo y está limpio. Yo ya no voy a tocar nada el hasta el lunes.
Que pases buen fin de semana.

**Comment by LanderU** [comment]
Con el siguiente [commit](https://github.com/AlbertoNietoGochicoa/DI_ProyectoFinal/pull/7/files) se soluciona.

**Comment by AlbertoNietoGochicoa** [comment]
ok, esta mañana me he estado peleando un rato, mañana a la mañana la hecho un vistazo a ver que puedo ir adelantando, un saludo y disfruta de tu tarde libre!!

**Comment by AlbertoNietoGochicoa** [comment]
He terminado el añadir producto y esta en el commit, luego me he puesto a hacer la de modificar producto y cuando ya la tenia practicamente terminada me ha pasado lo de ayer que se quedaba la ventana sin actualizar, cuando tenga un rato lo termino

**Comment by LanderU** [comment]
Si se rompe, antes de hacer los cambios y empujarlos. Deja en un commit aislado el problema, para poder revertir sólo ese cambio en caso de que siga sin funcionar.

Entiendo que es éste [commit](https://github.com/AlbertoNietoGochicoa/DI_ProyectoFinal/commit/48c83c475ffecb8308b575a107e48821c7a0d905) el que lo rompe.

**Comment by AlbertoNietoGochicoa** [comment]
He terminado el eliminar producto y he creado el procedure de modificar socio.
que pases buen finde ;)

**Comment by LanderU** [comment]
El fin de semana hago lo de la foto y demás no te preocupes. Buen fin de semana!!
